In [13]:
import numpy
folder="C:\\Users\\sriram\\OneDrive\\Fall 2016\\Data Mining\\Assignment\\Assignment 2\\"
inputFile="bcWiscon.txt"

dataArray=numpy.genfromtxt(folder+inputFile,delimiter=",",missing_values=('?'))

In [14]:
len(dataArray)

699

In [37]:
import scipy
def initialize(X, K):
    C = [X[0]]
    for k in range(1, K):
        D2 = scipy.array([min([scipy.inner(c-x,c-x) for c in C]) for x in X])
        print (D2)
        probs = D2/D2.sum()
        print (probs)
        cumprobs = probs.cumsum()
        print (cumprobs)
        r = scipy.rand()
        for j,p in enumerate(cumprobs):
            print (r,p)
            if r < p:
                i = j
                break
        C.append(X[i])
        print (C)
    return C

In [38]:
initialize([0,1,4,5,6,3,9], 3)

[ 0  1 16 25 36  9 81]
[ 0.          0.00595238  0.0952381   0.14880952  0.21428571  0.05357143
  0.48214286]
[ 0.          0.00595238  0.10119048  0.25        0.46428571  0.51785714
  1.        ]
0.1542999392297717 0.0
0.1542999392297717 0.00595238095238
0.1542999392297717 0.10119047619
0.1542999392297717 0.25
[0, 5]
[ 0  1  1  0  1  4 16]
[ 0.          0.04347826  0.04347826  0.          0.04347826  0.17391304
  0.69565217]
[ 0.          0.04347826  0.08695652  0.08695652  0.13043478  0.30434783
  1.        ]
0.19215322216270125 0.0
0.19215322216270125 0.0434782608696
0.19215322216270125 0.0869565217391
0.19215322216270125 0.0869565217391
0.19215322216270125 0.130434782609
0.19215322216270125 0.304347826087
[0, 5, 3]


[0, 5, 3]

In [32]:
m=scipy.array([1,2,3,4,5])

In [33]:
m/m.sum()

array([ 0.06666667,  0.13333333,  0.2       ,  0.26666667,  0.33333333])