In [6]:
import itertools
import numpy as np
inputData = np.array(list(itertools.product([0, 1], repeat=2)))
#learning rate
n=0.5
ErrorList=[]
#Change the y value to [0,1,1,0] for 4)d)
y=np.array([0,0,1,1])
weights=np.zeros(len(inputData[0])+1)
WeightList=[]
print (weights)
for j in range(100):
    #print ("Epoch :",j+1)
    errors=0
    for i in range(len(inputData)):
        #print(np.dot(inputData[i],weights[1:]))
        d=0 if weights[0]+np.dot(inputData[i],weights[1:])<=0 else 1
        deltaw=n*(y[i]-d)
        weights[1:]+=deltaw*inputData[i]
        weights[0]+=deltaw
        WeightList.append(weights)
        print (weights)
        errors+=int(deltaw!=0.0)
    ErrorList.append(errors)
    if errors==0:
        print ('0 Error achieved at Iteration',j+1)
        break

[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.  0.  0.]
[ 0.5  0.5  0. ]
[ 0.5  0.5  0. ]
[ 0.   0.5  0. ]
[ 0.   0.5  0. ]
[ 0.   0.5  0. ]
[ 0.   0.5  0. ]
[ 0.   0.5  0. ]
[ 0.   0.5  0. ]
[ 0.   0.5  0. ]
[ 0.   0.5  0. ]
0 Error achieved at Iteration 3


In [2]:
#learning rate=0.1
n=0.5
ErrorList=[]

weights1=np.zeros(shape=(1,len(inputData[0])+1))
weights2=np.zeros(len(inputData[0])+1)

In [ ]:
rows=layers=weights1.shape[0]
cols=weights1.shape[1]
for i in range(rows):
    for j in range(cols):
        weights1[i][j]=np.random.uniform(-1, 1)
        weights2[j]=np.random.uniform(-1, 1)

print(weights1,weights2)

In [ ]:
print(rows,cols,weights2.shape)

In [34]:
network=initialize_network(4,4,1)
row = [1, 1, 1,0]
output = forward_propagate(network, row)

In [35]:
output

[0.64298299514854973]

In [ ]:

for j in range(layers):
    for i in range(len(inputData)):
        #print(np.dot(inputData[i],weights[1:]))
        v=weights1[j,0]+np.dot(inputData[i],weights1[j,1:])
        d=1/(1+np.exp(-1*v))
        deltaw=n*(y[i]-d)
        weights1[j,1:]+=deltaw*inputData[i]
        weights1[j,0]+=deltaw

In [ ]:
weights

In [ ]:
ErrorList

In [ ]:
inputData2 = np.array(list(itertools.product([0, 1], repeat=4)))

In [ ]:
print(inputData2,y2)

In [ ]:
y2=np.zeros(len(inputData2))
z2=np.zeros(len(inputData2))
print('u','w','c','y')
for i in range(len(inputData2)):
    data=inputData2[i]
    uv=str(data[0])+str(data[1])
    wx=str(data[2])+str(data[3])
    value=ab(uv,wx)
    y2[i]=int(value[0] if len(value)==2 else value[1])
    z2[i]=int(value[1] if len(value)==2 else value[2])
    print(data[0],data[2],0 if len(value)==2 else 1,value[1] if len(value)==2 else value[2])


In [ ]:
#learning rate=0.1
n=0.1
ErrorList=[]
y=np.array([-1,-1,-1,1,-1,-1,-1,-1])
weights=np.zeros(len(inputData2[0])+1)
WeightList=[]
print (weights)
for j in range(10):
    errors=0
    for i in range(len(inputData2)):
        row=np.zeros(len(inputData2[0]))
        for k in range(len(inputData2[i])):
            row[k]=-1 if inputData2[i][k]==0 else 1
        d=1 if weights[0]+np.dot(row,weights[1:])>=0 else -1
        #print(weights[0]+np.dot(inputData2[i],weights[1:]),y2[i])
        deltaw=n*(z2[i]-d)
        weights[1:]+=deltaw*row
        weights[0]+=deltaw
        print(weights)
        WeightList.append(weights)
        errors+=int(deltaw!=0.0)
    print("New Iteration")
    ErrorList.append(errors)

In [ ]:
ErrorList

In [ ]:
ErrorList

In [ ]:
inputData2

In [ ]:
def ab(b1, b2):
    if not (b1 and b2):  # b1 or b2 is empty
        return b1 + b2
    head = ab(b1[:-1], b2[:-1])
    if b1[-1] == '0':  # 0+1 or 0+0
        return head + b2[-1]
    if b2[-1] == '0':  # 1+0
        return head + '1'
    #      V    NOTE   V <<< push overflow 1 to head
    return ab(head, '1') + '0'

In [ ]:
ab('00','10')

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
print('Weights: %s' % ppn.w_)
print(ppn.errors_)