In [1]:
import pandas as pd
import os
import csv

labels = {'pos':1, 'neg':0,'other':2}

In [289]:
#TrainData
folder="C:\\Users\\sriram\\OneDrive\\Computational Linguistics\\Final Project\\Targets\\Train\\"
file="train.csv"
df=pd.DataFrame()
Count=0
with open(os.path.join(folder, file), 'r', encoding='ISO-8859-1') as infile:
    reader = csv.reader(infile,skipinitialspace=True)
    for row in reader:
        if Count>0:
            df = df.append([[row[0],row[1],labels[row[4]]]], ignore_index=True)
        Count+=1
df.columns = ['Tweet','Target', 'Stance']
arguTrain=pd.read_csv(folder+"ArgLex Features\\"+"ArgFeatures-train.csv")

In [290]:
FinalDf=pd.concat([df.reset_index(drop=True), arguTrain.reset_index(drop=True)], axis=1)
df=FinalDf

In [330]:
#TestData
folder="C:\\Users\\sriram\\OneDrive\\Computational Linguistics\\Final Project\\Targets\\Test\\"
file="test.csv"
dfTest=pd.DataFrame()
Count=0
with open(os.path.join(folder, file), 'r', encoding='ISO-8859-1') as infile:
    reader = csv.reader(infile,skipinitialspace=True)
    for row in reader:
        if Count>0:
            dfTest = dfTest.append([[row[0],row[1],labels[row[4]]]], ignore_index=True)
        Count+=1
dfTest.columns = ['Tweet','Target', 'Stance']
arguTest=pd.read_csv(folder+"ArgLex Features\\"+"ArgFeatures-test.csv")
FinalDftest=pd.concat([dfTest.reset_index(drop=True), arguTest.reset_index(drop=True)], axis=1)

dfTest=FinalDftest

In [309]:
dfTest.shape

(1956, 20)

In [301]:
#Creating Separate datasets for each Target
HillaryTrain=df.loc[df.Target=="Hillary Clinton"]
AtheismTrain=df.loc[df.Target=="Atheism"]
AbortionTrain=df.loc[df.Target=="Legalization of Abortion"]
FeministTrain=df.loc[df.Target=="Feminist Movement"]
ClimateTrain=df.loc[df.Target=="Climate Change is a Real Concern"]

In [302]:
#Creating Separate datasets for each Target
HillaryTest=dfTest.loc[dfTest.Target=="Hillary Clinton"]
AtheismTest=dfTest.loc[dfTest.Target=="Atheism"]
AbortionTest=dfTest.loc[dfTest.Target=="Legalization of Abortion"]
FeministTest=dfTest.loc[dfTest.Target=="Feminist Movement"]
ClimateTest=dfTest.loc[dfTest.Target=="Climate Change is a Real Concern"]

In [7]:
#Transforming documents into feature vectors
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
docs = np.array([
        'The sun is shining',
        'The weather is sweet',
        'The sun is shining and the weather is sweet'])
bag = count.fit_transform(docs)

In [38]:
print(count.vocabulary_)

{'is': 1, 'and': 0, 'sweet': 4, 'the': 5, 'sun': 3, 'weather': 6, 'shining': 2}


In [39]:
print(bag.toarray())

[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 2 1]]


In [8]:
#Assessing word relevancy via term frequency-inverse document frequency
np.set_printoptions(precision=2)
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[ 0.    0.43  0.56  0.56  0.    0.43  0.  ]
 [ 0.    0.43  0.    0.    0.56  0.43  0.56]
 [ 0.4   0.48  0.31  0.31  0.31  0.48  0.31]]


In [9]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sriram\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
from nltk.corpus import stopwords
from utils import *
stop = stopwords.words('english')
print (stop)
[w for w in tokenizer('a runner likes running and runs a lot')[-10:] if w not in stop]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', 'should', 'no

[]

In [23]:
tokenizer(":-)Happy :-( Sad")

[':-)', 'Happy', ':-(', 'Sad']

In [206]:
X_train.head()

Tweet
0  Hillary is our best choice if we truly want to...
1  @TheView I think our country is ready for a fe...
2  I just gave an unhealthy amount of my hard-ear...
3  @PortiaABoulger Thank you for adding me to you...
4  Hillary can not win. Here's hoping the Dems of...

In [61]:
check=df.ix[:,0:1]
check2=df.ix[:,3:4]
print (np.concatenate([check,check2], axis=1)[1])

[ "@TheView I think our country is ready for a female pres, it can't ever be Hillary"
 0]


In [448]:
from utils import *
from sklearn.grid_search import GridSearchCV
from sklearn.pipeline import Pipeline,FeatureUnion
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer


import numpy as np


tfidf = TfidfVectorizer(strip_accents=None, 
                        lowercase=False, 
                        preprocessor=None)

#param_grid = [{'vect__ngram_range': [(1,1)],
#               'vect__stop_words': [stop],
#               'vect__tokenizer': [tokenizer],
#               'clf__penalty': ['l1', 'l2'],
#               'clf__C': [1.0, 10.0, 100.0],
#              'vect__max_features':[1500,1600,1700]}]
#
#param_grid = [{'vect__ngram_range': [(1,1)],
#               'vect__stop_words': [stop],
#               'vect__tokenizer': [tokenizer],
#               'clf__n_estimators': [10,15,20],
#               'clf__min_samples_leaf':[5,10],
#              'vect__max_features':[500,750,1000,1250,1500,1750,2000]},
#             {'vect__ngram_range': [(1,1)],
#               'vect__stop_words': [stop],
#               'vect__tokenizer': [tokenizer],
#               'clf__n_estimators': [10,15,20,25,50,100],
#               'clf__min_samples_leaf':[3,5,10],
#              'vect__max_features':[500,750,1000,1250,1500,1750,2000,2500]}]
param_grid = [{'vect__ngram_range': [(1,1)],
               'vect__stop_words': [stop],
               'vect__tokenizer': [tokenizer],
               'clf__n_estimators': [10,15,20,25,50,100],
               'clf__min_samples_leaf':[5,10],
              'vect__max_features':[500,750,1000,1250,1500,1750,2000,2500]}]

lr_tfidf = Pipeline([('vect', tfidf),
                    ('clf', RandomForestClassifier())])


mh=mat=mab=mc=mf = GridSearchCV(lr_tfidf, param_grid, 
                           scoring='accuracy',
                           cv=5, verbose=1,
                           n_jobs=-1)




In [6]:
a=[1,221,31,43,4,-1]
a=sorted(a)
print(a)

[-1, 1, 4, 31, 43, 221]


In [449]:
mh.fit(HillaryTrain['Tweet'].values,HillaryTrain.Stance)
print('ModelHilary Best parameter set: %s ' % mh.best_params_)
print('ModelHilary CV Accuracy: %.3f' % mh.best_score_)
clf = mh.best_estimator_
print('Test Accuracy: %.3f' % clf.score(HillaryTest['Tweet'], HillaryTest.Stance))
print()


mat.fit(AtheismTrain['Tweet'].values,AtheismTrain.Stance)
print('ModelAtheism Best parameter set: %s ' % mat.best_params_)
print('ModelAtheism CV Accuracy: %.3f' % mat.best_score_)
clf = mat.best_estimator_
print('Test Accuracy: %.3f' % clf.score(AtheismTest['Tweet'], AtheismTest.Stance))
print()


mab.fit(AbortionTrain['Tweet'].values,AbortionTrain.Stance)
print('ModelAbortion Best parameter set: %s ' % mab.best_params_)
print('ModelAbortion CV Accuracy: %.3f' % mab.best_score_)
clf = mab.best_estimator_
print('Test Accuracy: %.3f' % clf.score(AbortionTest['Tweet'], AbortionTest.Stance))
print()


mc.fit(ClimateTrain['Tweet'].values,ClimateTrain.Stance)
print('ModelClimate Best parameter set: %s ' % mc.best_params_)
print('ModelClimate CV Accuracy: %.3f' % mc.best_score_)
clf = mc.best_estimator_
print('Test Accuracy: %.3f' % clf.score(ClimateTest['Tweet'], ClimateTest.Stance))
print()


mf.fit(FeministTrain['Tweet'].values,FeministTrain.Stance)
print('ModelFeminist Best parameter set: %s ' % mf.best_params_)
print('ModelFeminist CV Accuracy: %.3f' % mf.best_score_)
clf = mf.best_estimator_
print('Test Accuracy: %.3f' % clf.score(FeministTest['Tweet'], FeministTest.Stance))
print()


Fitting 5 folds for each of 96 candidates, totalling 480 fits


[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   25.6s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   32.4s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:   44.8s
[Parallel(n_jobs=-1)]: Done 480 out of 480 | elapsed:   48.3s finished


ModelHilary Best parameter set: {'vect__tokenizer': <function tokenizer at 0x000002AEF76C06A8>, 'vect__stop_words': ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'no

[Parallel(n_jobs=-1)]: Done  43 tasks      | elapsed:    5.5s
[Parallel(n_jobs=-1)]: Done 343 tasks      | elapsed:   17.0s
[Parallel(n_jobs=-1)]: Done 473 out of 480 | elapsed:   23.9s remaining:    0.3s
[Parallel(n_jobs=-1)]: Done 480 out of 480 | elapsed:   24.3s finished


ModelAtheism Best parameter set: {'vect__tokenizer': <function tokenizer at 0x000002AEF76C06A8>, 'vect__stop_words': ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'n

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    5.9s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   12.2s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:   24.7s
[Parallel(n_jobs=-1)]: Done 480 out of 480 | elapsed:   28.3s finished


ModelAbortion Best parameter set: {'vect__tokenizer': <function tokenizer at 0x000002AEF76C06A8>, 'vect__stop_words': ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', '

[Parallel(n_jobs=-1)]: Done  45 tasks      | elapsed:    5.8s
[Parallel(n_jobs=-1)]: Done 345 tasks      | elapsed:   16.4s
[Parallel(n_jobs=-1)]: Done 473 out of 480 | elapsed:   22.5s remaining:    0.2s
[Parallel(n_jobs=-1)]: Done 480 out of 480 | elapsed:   22.9s finished


ModelClimate Best parameter set: {'vect__tokenizer': <function tokenizer at 0x000002AEF76C06A8>, 'vect__stop_words': ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'n

[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    5.7s
[Parallel(n_jobs=-1)]: Done 192 tasks      | elapsed:   11.9s
[Parallel(n_jobs=-1)]: Done 442 tasks      | elapsed:   23.4s
[Parallel(n_jobs=-1)]: Done 480 out of 480 | elapsed:   26.4s finished


ModelFeminist Best parameter set: {'vect__tokenizer': <function tokenizer at 0x000002AEF76C06A8>, 'vect__stop_words': ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', '

In [425]:
#Baseline
from collections import Counter
data = Counter(HillaryTrain.Stance)
print("Hillary Baseline",data,np.mean(HillaryTest.Stance==data.most_common(1)[0][0]))
data = Counter(AbortionTrain.Stance)
print("Abortion Baseline",data,np.mean(AbortionTest.Stance==data.most_common(1)[0][0]))
data = Counter(AtheismTrain.Stance)
print("Atheism Baseline",data,np.mean(AtheismTest.Stance==data.most_common(1)[0][0]))
data = Counter(ClimateTrain.Stance)
print("Climate Baseline",data,np.mean(ClimateTest.Stance==data.most_common(1)[0][0]))
data = Counter(FeministTrain.Stance)
print("Feminist Baseline",data,np.mean(FeministTest.Stance==data.most_common(1)[0][0]))


Hillary Baseline Counter({0: 441, 1: 221, 2: 27}) 0.701694915254
Abortion Baseline Counter({0: 432, 1: 188, 2: 33}) 0.721428571429
Atheism Baseline Counter({1: 310, 0: 180, 2: 23}) 0.590909090909
Climate Baseline Counter({0: 196, 1: 125, 2: 74}) 0.514792899408
Feminist Baseline Counter({0: 513, 1: 119, 2: 32}) 0.761403508772


In [443]:
from sklearn.metrics import precision_recall_fscore_support as score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
data = Counter(HillaryTrain.Stance)
precision, recall, fscore, support=score(HillaryTest.Stance,[data.most_common(1)[0][0]]*HillaryTest.shape[0])
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(fscore))
print('support: {}'.format(support))
print (confusion_matrix(HillaryTest.Stance,[data.most_common(1)[0][0]]*HillaryTest.shape[0]))

precision: [ 0.7  0.   0. ]
recall: [ 1.  0.  0.]
fscore: [ 0.82  0.    0.  ]
support: [207  76  12]
[[207   0   0]
 [ 76   0   0]
 [ 12   0   0]]


C:\Users\sriram\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [445]:
precision, recall, fscore, support=score(HillaryTest.Stance,clf.predict(HillaryTest['Tweet']))
clf = mh.best_estimator_
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print('fscore: {}'.format(fscore))
print('support: {}'.format(support))
print (confusion_matrix(HillaryTest.Stance,clf.predict(HillaryTest['Tweet'])))

precision: [ 0.7  0.5  0. ]
recall: [ 1.    0.01  0.  ]
fscore: [ 0.82  0.03  0.  ]
support: [207  76  12]
[[206   1   0]
 [ 75   1   0]
 [ 12   0   0]]


C:\Users\sriram\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [447]:
207/sum(support)

0.70169491525423733

In [ ]:
#Training a logistic regression model for document classification
X_train = df.ix[:,0:1]
y_train = df['Stance']
X_test = dfTest.ix[:,0:1]
y_test = dfTest['Stance']

In [381]:
from utils import *
from sklearn.feature_extraction.text import TfidfVectorizer
#count_vect = CountVectorizer()
#X_train_counts = count_vect.fit_transform(df['Tweet'].values.astype('U'))
tf= TfidfVectorizer(strip_accents=None, 
                        lowercase=False, 
                        preprocessor=None,
                        tokenizer=tokenizer11,
                        max_features=1500)
X_Train=tf.fit_transform(list(df['Tweet']))
X_Test=tf.fit_transform(list(dfTest['Tweet']))
#print(count_vect.vocabulary_.get(u'hilary'))

In [382]:
X_Train=X_Train.toarray()
X_Train = np.append(X_Train, df.ix[:,3:10].values, 1)
X_Test=X_Test.toarray()
X_Test = np.append(X_Test, dfTest.ix[:,3:10].values, 1)
print(X_Train.shape)
print(X_Test.shape)

(2914, 1507)
(1956, 1507)


In [168]:
from sklearn.preprocessing import Imputer
all_data = Imputer().fit_transform(all_data)

In [388]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import log_loss
clf=LogisticRegression(random_state=0, multi_class='ovr',penalty='l2',C=1.0)
clf.fit(X_Train,df.Stance)
clf2 = RandomForestClassifier(n_estimators=25,min_samples_leaf=5)
print (X_Train)
clf2.fit(X_Train, df.Stance)

[[ 0.    0.    0.   ...,  0.    0.    0.  ]
 [ 0.    0.    0.   ...,  0.    0.    0.  ]
 [ 0.    0.    0.   ...,  0.    0.    0.  ]
 ..., 
 [ 0.    0.    0.   ...,  0.    0.    0.  ]
 [ 0.    0.    0.   ...,  0.    0.    0.  ]
 [ 0.23  0.    0.   ...,  0.    0.    0.  ]]


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=25, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [389]:
print(np.mean(clf.predict(X_Test) == dfTest.Stance) )
print(np.mean(clf2.predict(X_Test) == dfTest.Stance) )

0.626789366053
0.609918200409


Best parameter set: {'vect__tokenizer': <function tokenizer at 0x000002AEF76C06A8>, 'vect__stop_words': ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', 'her', 'hers', 'herself', 'it', 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', '

Test Accuracy: 0.685


In [395]:
np.mean(clf.predict(HillaryTest['Tweet'])==HillaryTest.Stance)

0.68474576271186438